name: Static-Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4

    - name: Install cppcheck
      run: |
        winget install -e --id Cppcheck.Cppcheck --accept-source-agreements --accept-package-agreements
      shell: cmd

    - name: Cppcheck
      working-directory: ${{github.workspace}}
      run: |
        cppcheck ./lib/src \
        -I ./lib/include/ \
        --enable=all \
        --suppress=unusedFunction \
        --suppress=missingIncludeSystem
      shell: cmd
